name: Auto Merge

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened, edited, ready_for_review, reopened]
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]
  status: {}

jobs:
  auto-merge:
    name: Auto Merge PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: read
    if: |
      github.event_name == 'pull_request' ||
      github.event_name == 'pull_request_review' ||
      github.event_name == 'check_suite' ||
      github.event_name == 'status'
    
    steps:
    - name: Auto merge
      uses: pascalgn/automerge-action@v0.16.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MERGE_METHOD: squash
        MERGE_LABELS: "auto-merge,!no-merge"
